// Code generated by MockGen. DO NOT EDIT.
// Source: internal/daemon/dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agterm "github.com/k0nsta/agterm-remote/internal/agterm"
	daemon "github.com/k0nsta/agterm-remote/internal/daemon"
	remote "github.com/k0nsta/agterm-remote/internal/remote"
	gomock "go.uber.org/mock/gomock"
)

// MockUI is a mock of UI interface.
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *MockUIMockRecorder
}

// MockUIMockRecorder is the mock recorder for MockUI.
type MockUIMockRecorder struct {
	mock *MockUI
}

// NewMockUI creates a new mock instance.
func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &MockUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUI) EXPECT() *MockUIMockRecorder {
	return m.recorder
}

// HudClose mocks base method.
func (m *MockUI) HudClose(ctx context.Context, row string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HudClose", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// HudClose indicates an expected call of HudClose.
func (mr *MockUIMockRecorder) HudClose(ctx, row interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HudClose", reflect.TypeOf((*MockUI)(nil).HudClose), ctx, row)
}

// HudOpen mocks base method.
func (m *MockUI) HudOpen(ctx context.Context, row, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HudOpen", ctx, row, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// HudOpen indicates an expected call of HudOpen.
func (mr *MockUIMockRecorder) HudOpen(ctx, row, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HudOpen", reflect.TypeOf((*MockUI)(nil).HudOpen), ctx, row, message)
}

// MockRemote is a mock of Remote interface.
type MockRemote struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteMockRecorder
}

// MockRemoteMockRecorder is the mock recorder for MockRemote.
type MockRemoteMockRecorder struct {
	mock *MockRemote
}

// NewMockRemote creates a new mock instance.
func NewMockRemote(ctrl *gomock.Controller) *MockRemote {
	mock := &MockRemote{ctrl: ctrl}
	mock.recorder = &MockRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemote) EXPECT() *MockRemoteMockRecorder {
	return m.recorder
}

// EnsureDirs mocks base method.
func (m *MockRemote) EnsureDirs(ctx context.Context, host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDirs", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDirs indicates an expected call of EnsureDirs.
func (mr *MockRemoteMockRecorder) EnsureDirs(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDirs", reflect.TypeOf((*MockRemote)(nil).EnsureDirs), ctx, host)
}

// Home mocks base method.
func (m *MockRemote) Home(ctx context.Context, host string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Home", ctx, host)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Home indicates an expected call of Home.
func (mr *MockRemoteMockRecorder) Home(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Home", reflect.TypeOf((*MockRemote)(nil).Home), ctx, host)
}

// Sessions mocks base method.
func (m *MockRemote) Sessions(ctx context.Context, host string) ([]remote.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions", ctx, host)
	ret0, _ := ret[0].([]remote.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sessions indicates an expected call of Sessions.
func (mr *MockRemoteMockRecorder) Sessions(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockRemote)(nil).Sessions), ctx, host)
}

// MockEventSource is a mock of EventSource interface.
type MockEventSource struct {
	ctrl     *gomock.Controller
	recorder *MockEventSourceMockRecorder
}

// MockEventSourceMockRecorder is the mock recorder for MockEventSource.
type MockEventSourceMockRecorder struct {
	mock *MockEventSource
}

// NewMockEventSource creates a new mock instance.
func NewMockEventSource(ctrl *gomock.Controller) *MockEventSource {
	mock := &MockEventSource{ctrl: ctrl}
	mock.recorder = &MockEventSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSource) EXPECT() *MockEventSourceMockRecorder {
	return m.recorder
}

// ClosedRows mocks base method.
func (m *MockEventSource) ClosedRows(ctx context.Context) (<-chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClosedRows", ctx)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClosedRows indicates an expected call of ClosedRows.
func (mr *MockEventSourceMockRecorder) ClosedRows(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClosedRows", reflect.TypeOf((*MockEventSource)(nil).ClosedRows), ctx)
}

// MockRows is a mock of Rows interface.
type MockRows struct {
	ctrl     *gomock.Controller
	recorder *MockRowsMockRecorder
}

// MockRowsMockRecorder is the mock recorder for MockRows.
type MockRowsMockRecorder struct {
	mock *MockRows
}

// NewMockRows creates a new mock instance.
func NewMockRows(ctrl *gomock.Controller) *MockRows {
	mock := &MockRows{ctrl: ctrl}
	mock.recorder = &MockRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRows) EXPECT() *MockRowsMockRecorder {
	return m.recorder
}

// Tree mocks base method.
func (m *MockRows) Tree(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tree indicates an expected call of Tree.
func (mr *MockRowsMockRecorder) Tree(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockRows)(nil).Tree), ctx)
}

// MockStatusSink is a mock of StatusSink interface.
type MockStatusSink struct {
	ctrl     *gomock.Controller
	recorder *MockStatusSinkMockRecorder
}

// MockStatusSinkMockRecorder is the mock recorder for MockStatusSink.
type MockStatusSinkMockRecorder struct {
	mock *MockStatusSink
}

// NewMockStatusSink creates a new mock instance.
func NewMockStatusSink(ctrl *gomock.Controller) *MockStatusSink {
	mock := &MockStatusSink{ctrl: ctrl}
	mock.recorder = &MockStatusSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusSink) EXPECT() *MockStatusSinkMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockStatusSink) Status(ctx context.Context, target string, args agterm.StatusArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, target, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockStatusSinkMockRecorder) Status(ctx, target, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStatusSink)(nil).Status), ctx, target, args)
}

// MockSupervisor is a mock of Supervisor interface.
type MockSupervisor struct {
	ctrl     *gomock.Controller
	recorder *MockSupervisorMockRecorder
}

// MockSupervisorMockRecorder is the mock recorder for MockSupervisor.
type MockSupervisorMockRecorder struct {
	mock *MockSupervisor
}

// NewMockSupervisor creates a new mock instance.
func NewMockSupervisor(ctrl *gomock.Controller) *MockSupervisor {
	mock := &MockSupervisor{ctrl: ctrl}
	mock.recorder = &MockSupervisorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupervisor) EXPECT() *MockSupervisorMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockSupervisor) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockSupervisorMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSupervisor)(nil).Run), ctx)
}

// Stop mocks base method.
func (m *MockSupervisor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSupervisorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSupervisor)(nil).Stop))
}

// MockSupervisors is a mock of Supervisors interface.
type MockSupervisors struct {
	ctrl     *gomock.Controller
	recorder *MockSupervisorsMockRecorder
}

// MockSupervisorsMockRecorder is the mock recorder for MockSupervisors.
type MockSupervisorsMockRecorder struct {
	mock *MockSupervisors
}

// NewMockSupervisors creates a new mock instance.
func NewMockSupervisors(ctrl *gomock.Controller) *MockSupervisors {
	mock := &MockSupervisors{ctrl: ctrl}
	mock.recorder = &MockSupervisorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupervisors) EXPECT() *MockSupervisorsMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockSupervisors) New(host, hostKey, remoteSock, localSock string) daemon.Supervisor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", host, hostKey, remoteSock, localSock)
	ret0, _ := ret[0].(daemon.Supervisor)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockSupervisorsMockRecorder) New(host, hostKey, remoteSock, localSock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockSupervisors)(nil).New), host, hostKey, remoteSock, localSock)
}
