// Code generated by MockGen. DO NOT EDIT.
// Source: dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agterm "github.com/k0nsta/agterm-remote/internal/agterm"
	bindings "github.com/k0nsta/agterm-remote/internal/bindings"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusSink is a mock of StatusSink interface.
type MockStatusSink struct {
	ctrl     *gomock.Controller
	recorder *MockStatusSinkMockRecorder
	isgomock struct{}
}

// MockStatusSinkMockRecorder is the mock recorder for MockStatusSink.
type MockStatusSinkMockRecorder struct {
	mock *MockStatusSink
}

// NewMockStatusSink creates a new mock instance.
func NewMockStatusSink(ctrl *gomock.Controller) *MockStatusSink {
	mock := &MockStatusSink{ctrl: ctrl}
	mock.recorder = &MockStatusSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusSink) EXPECT() *MockStatusSinkMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockStatusSink) Status(ctx context.Context, target string, args agterm.StatusArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, target, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockStatusSinkMockRecorder) Status(ctx, target, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStatusSink)(nil).Status), ctx, target, args)
}

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// ByHostName mocks base method.
func (m *MockResolver) ByHostName(host, name string) (bindings.Binding, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByHostName", host, name)
	ret0, _ := ret[0].(bindings.Binding)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ByHostName indicates an expected call of ByHostName.
func (mr *MockResolverMockRecorder) ByHostName(host, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByHostName", reflect.TypeOf((*MockResolver)(nil).ByHostName), host, name)
}

// MockLiveness is a mock of Liveness interface.
type MockLiveness struct {
	ctrl     *gomock.Controller
	recorder *MockLivenessMockRecorder
	isgomock struct{}
}

// MockLivenessMockRecorder is the mock recorder for MockLiveness.
type MockLivenessMockRecorder struct {
	mock *MockLiveness
}

// NewMockLiveness creates a new mock instance.
func NewMockLiveness(ctrl *gomock.Controller) *MockLiveness {
	mock := &MockLiveness{ctrl: ctrl}
	mock.recorder = &MockLivenessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveness) EXPECT() *MockLivenessMockRecorder {
	return m.recorder
}

// MarkAlive mocks base method.
func (m *MockLiveness) MarkAlive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkAlive")
}

// MarkAlive indicates an expected call of MarkAlive.
func (mr *MockLivenessMockRecorder) MarkAlive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAlive", reflect.TypeOf((*MockLiveness)(nil).MarkAlive))
}
