// Code generated by MockGen. DO NOT EDIT.
// Source: dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	bridge "github.com/k0nsta/agterm-remote/internal/bridge"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessRunner is a mock of ProcessRunner interface.
type MockProcessRunner struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRunnerMockRecorder
}

// MockProcessRunnerMockRecorder is the mock recorder for MockProcessRunner.
type MockProcessRunnerMockRecorder struct {
	mock *MockProcessRunner
}

// NewMockProcessRunner creates a new mock instance.
func NewMockProcessRunner(ctrl *gomock.Controller) *MockProcessRunner {
	mock := &MockProcessRunner{ctrl: ctrl}
	mock.recorder = &MockProcessRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRunner) EXPECT() *MockProcessRunnerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockProcessRunner) Start(ctx context.Context, argv []string, logPath string) (bridge.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, argv, logPath)
	ret0, _ := ret[0].(bridge.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockProcessRunnerMockRecorder) Start(ctx, argv, logPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProcessRunner)(nil).Start), ctx, argv, logPath)
}

// MockProcess is a mock of Process interface.
type MockProcess struct {
	ctrl     *gomock.Controller
	recorder *MockProcessMockRecorder
}

// MockProcessMockRecorder is the mock recorder for MockProcess.
type MockProcessMockRecorder struct {
	mock *MockProcess
}

// NewMockProcess creates a new mock instance.
func NewMockProcess(ctrl *gomock.Controller) *MockProcess {
	mock := &MockProcess{ctrl: ctrl}
	mock.recorder = &MockProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcess) EXPECT() *MockProcessMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockProcess) Stop(grace time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", grace)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockProcessMockRecorder) Stop(grace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockProcess)(nil).Stop), grace)
}

// Wait mocks base method.
func (m *MockProcess) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockProcessMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockProcess)(nil).Wait))
}
