// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cli/dependency.go
//
// Generated by this command:
//
//	mockgen -source=internal/cli/dependency.go -destination=internal/cli/mocks/dependency_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agterm "github.com/k0nsta/agterm-remote/internal/agterm"
	remote "github.com/k0nsta/agterm-remote/internal/remote"
	gomock "go.uber.org/mock/gomock"
)

// MockPicker is a mock of Picker interface.
type MockPicker struct {
	ctrl     *gomock.Controller
	recorder *MockPickerMockRecorder
	isgomock struct{}
}

// MockPickerMockRecorder is the mock recorder for MockPicker.
type MockPickerMockRecorder struct {
	mock *MockPicker
}

// NewMockPicker creates a new mock instance.
func NewMockPicker(ctrl *gomock.Controller) *MockPicker {
	mock := &MockPicker{ctrl: ctrl}
	mock.recorder = &MockPickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPicker) EXPECT() *MockPickerMockRecorder {
	return m.recorder
}

// Pick mocks base method.
func (m *MockPicker) Pick(ctx context.Context, items []agterm.PickItem, prompt string) (agterm.PickResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pick", ctx, items, prompt)
	ret0, _ := ret[0].(agterm.PickResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pick indicates an expected call of Pick.
func (mr *MockPickerMockRecorder) Pick(ctx, items, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pick", reflect.TypeOf((*MockPicker)(nil).Pick), ctx, items, prompt)
}

// MockRows is a mock of Rows interface.
type MockRows struct {
	ctrl     *gomock.Controller
	recorder *MockRowsMockRecorder
	isgomock struct{}
}

// MockRowsMockRecorder is the mock recorder for MockRows.
type MockRowsMockRecorder struct {
	mock *MockRows
}

// NewMockRows creates a new mock instance.
func NewMockRows(ctrl *gomock.Controller) *MockRows {
	mock := &MockRows{ctrl: ctrl}
	mock.recorder = &MockRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRows) EXPECT() *MockRowsMockRecorder {
	return m.recorder
}

// Tree mocks base method.
func (m *MockRows) Tree(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tree indicates an expected call of Tree.
func (mr *MockRowsMockRecorder) Tree(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockRows)(nil).Tree), ctx)
}

// MockLabeler is a mock of Labeler interface.
type MockLabeler struct {
	ctrl     *gomock.Controller
	recorder *MockLabelerMockRecorder
	isgomock struct{}
}

// MockLabelerMockRecorder is the mock recorder for MockLabeler.
type MockLabelerMockRecorder struct {
	mock *MockLabeler
}

// NewMockLabeler creates a new mock instance.
func NewMockLabeler(ctrl *gomock.Controller) *MockLabeler {
	mock := &MockLabeler{ctrl: ctrl}
	mock.recorder = &MockLabelerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabeler) EXPECT() *MockLabelerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockLabeler) Context(ctx context.Context, row, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", ctx, row, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockLabelerMockRecorder) Context(ctx, row, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockLabeler)(nil).Context), ctx, row, text)
}

// Rename mocks base method.
func (m *MockLabeler) Rename(ctx context.Context, row, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, row, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockLabelerMockRecorder) Rename(ctx, row, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockLabeler)(nil).Rename), ctx, row, name)
}

// MockSessions is a mock of Sessions interface.
type MockSessions struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsMockRecorder
	isgomock struct{}
}

// MockSessionsMockRecorder is the mock recorder for MockSessions.
type MockSessionsMockRecorder struct {
	mock *MockSessions
}

// NewMockSessions creates a new mock instance.
func NewMockSessions(ctrl *gomock.Controller) *MockSessions {
	mock := &MockSessions{ctrl: ctrl}
	mock.recorder = &MockSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessions) EXPECT() *MockSessionsMockRecorder {
	return m.recorder
}

// Reap mocks base method.
func (m *MockSessions) Reap(ctx context.Context, host, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reap", ctx, host, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reap indicates an expected call of Reap.
func (mr *MockSessionsMockRecorder) Reap(ctx, host, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reap", reflect.TypeOf((*MockSessions)(nil).Reap), ctx, host, name)
}

// Sessions mocks base method.
func (m *MockSessions) Sessions(ctx context.Context, host string) ([]remote.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions", ctx, host)
	ret0, _ := ret[0].([]remote.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sessions indicates an expected call of Sessions.
func (mr *MockSessionsMockRecorder) Sessions(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockSessions)(nil).Sessions), ctx, host)
}
