// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cli/dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agterm "github.com/k0nsta/agterm-remote/internal/agterm"
	daemon "github.com/k0nsta/agterm-remote/internal/daemon"
	remote "github.com/k0nsta/agterm-remote/internal/remote"
	gomock "go.uber.org/mock/gomock"
)

// MockPicker is a mock of Picker interface.
type MockPicker struct {
	ctrl     *gomock.Controller
	recorder *MockPickerMockRecorder
}

// MockPickerMockRecorder is the mock recorder for MockPicker.
type MockPickerMockRecorder struct {
	mock *MockPicker
}

// NewMockPicker creates a new mock instance.
func NewMockPicker(ctrl *gomock.Controller) *MockPicker {
	mock := &MockPicker{ctrl: ctrl}
	mock.recorder = &MockPickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPicker) EXPECT() *MockPickerMockRecorder {
	return m.recorder
}

// Pick mocks base method.
func (m *MockPicker) Pick(ctx context.Context, items []agterm.PickItem, prompt string) (agterm.PickResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pick", ctx, items, prompt)
	ret0, _ := ret[0].(agterm.PickResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pick indicates an expected call of Pick.
func (mr *MockPickerMockRecorder) Pick(ctx, items, prompt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pick", reflect.TypeOf((*MockPicker)(nil).Pick), ctx, items, prompt)
}

// MockRows is a mock of Rows interface.
type MockRows struct {
	ctrl     *gomock.Controller
	recorder *MockRowsMockRecorder
}

// MockRowsMockRecorder is the mock recorder for MockRows.
type MockRowsMockRecorder struct {
	mock *MockRows
}

// NewMockRows creates a new mock instance.
func NewMockRows(ctrl *gomock.Controller) *MockRows {
	mock := &MockRows{ctrl: ctrl}
	mock.recorder = &MockRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRows) EXPECT() *MockRowsMockRecorder {
	return m.recorder
}

// Tree mocks base method.
func (m *MockRows) Tree(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tree indicates an expected call of Tree.
func (mr *MockRowsMockRecorder) Tree(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockRows)(nil).Tree), ctx)
}

// MockLabeler is a mock of Labeler interface.
type MockLabeler struct {
	ctrl     *gomock.Controller
	recorder *MockLabelerMockRecorder
}

// MockLabelerMockRecorder is the mock recorder for MockLabeler.
type MockLabelerMockRecorder struct {
	mock *MockLabeler
}

// NewMockLabeler creates a new mock instance.
func NewMockLabeler(ctrl *gomock.Controller) *MockLabeler {
	mock := &MockLabeler{ctrl: ctrl}
	mock.recorder = &MockLabelerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabeler) EXPECT() *MockLabelerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockLabeler) Context(ctx context.Context, row, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", ctx, row, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockLabelerMockRecorder) Context(ctx, row, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockLabeler)(nil).Context), ctx, row, text)
}

// Rename mocks base method.
func (m *MockLabeler) Rename(ctx context.Context, row, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, row, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockLabelerMockRecorder) Rename(ctx, row, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockLabeler)(nil).Rename), ctx, row, name)
}

// MockSessions is a mock of Sessions interface.
type MockSessions struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsMockRecorder
}

// MockSessionsMockRecorder is the mock recorder for MockSessions.
type MockSessionsMockRecorder struct {
	mock *MockSessions
}

// NewMockSessions creates a new mock instance.
func NewMockSessions(ctrl *gomock.Controller) *MockSessions {
	mock := &MockSessions{ctrl: ctrl}
	mock.recorder = &MockSessionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessions) EXPECT() *MockSessionsMockRecorder {
	return m.recorder
}

// Reap mocks base method.
func (m *MockSessions) Reap(ctx context.Context, host, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reap", ctx, host, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reap indicates an expected call of Reap.
func (mr *MockSessionsMockRecorder) Reap(ctx, host, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reap", reflect.TypeOf((*MockSessions)(nil).Reap), ctx, host, name)
}

// Sessions mocks base method.
func (m *MockSessions) Sessions(ctx context.Context, host string) ([]remote.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions", ctx, host)
	ret0, _ := ret[0].([]remote.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sessions indicates an expected call of Sessions.
func (mr *MockSessionsMockRecorder) Sessions(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockSessions)(nil).Sessions), ctx, host)
}

// MockInstaller is a mock of Installer interface.
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller.
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance.
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockInstaller) Install(ctx context.Context, host, mux string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, host, mux)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockInstallerMockRecorder) Install(ctx, host, mux interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockInstaller)(nil).Install), ctx, host, mux)
}

// MockVersioner is a mock of Versioner interface.
type MockVersioner struct {
	ctrl     *gomock.Controller
	recorder *MockVersionerMockRecorder
}

// MockVersionerMockRecorder is the mock recorder for MockVersioner.
type MockVersionerMockRecorder struct {
	mock *MockVersioner
}

// NewMockVersioner creates a new mock instance.
func NewMockVersioner(ctrl *gomock.Controller) *MockVersioner {
	mock := &MockVersioner{ctrl: ctrl}
	mock.recorder = &MockVersionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersioner) EXPECT() *MockVersionerMockRecorder {
	return m.recorder
}

// Version mocks base method.
func (m *MockVersioner) Version(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockVersionerMockRecorder) Version(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockVersioner)(nil).Version), ctx)
}

// MockAgtermInspector is a mock of AgtermInspector interface.
type MockAgtermInspector struct {
	ctrl     *gomock.Controller
	recorder *MockAgtermInspectorMockRecorder
}

// MockAgtermInspectorMockRecorder is the mock recorder for MockAgtermInspector.
type MockAgtermInspectorMockRecorder struct {
	mock *MockAgtermInspector
}

// NewMockAgtermInspector creates a new mock instance.
func NewMockAgtermInspector(ctrl *gomock.Controller) *MockAgtermInspector {
	mock := &MockAgtermInspector{ctrl: ctrl}
	mock.recorder = &MockAgtermInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgtermInspector) EXPECT() *MockAgtermInspectorMockRecorder {
	return m.recorder
}

// RestoreMode mocks base method.
func (m *MockAgtermInspector) RestoreMode(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreMode", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreMode indicates an expected call of RestoreMode.
func (mr *MockAgtermInspectorMockRecorder) RestoreMode(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreMode", reflect.TypeOf((*MockAgtermInspector)(nil).RestoreMode), ctx)
}

// SupportsContext mocks base method.
func (m *MockAgtermInspector) SupportsContext(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsContext", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SupportsContext indicates an expected call of SupportsContext.
func (mr *MockAgtermInspectorMockRecorder) SupportsContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsContext", reflect.TypeOf((*MockAgtermInspector)(nil).SupportsContext), ctx)
}

// MockProber is a mock of Prober interface.
type MockProber struct {
	ctrl     *gomock.Controller
	recorder *MockProberMockRecorder
}

// MockProberMockRecorder is the mock recorder for MockProber.
type MockProberMockRecorder struct {
	mock *MockProber
}

// NewMockProber creates a new mock instance.
func NewMockProber(ctrl *gomock.Controller) *MockProber {
	mock := &MockProber{ctrl: ctrl}
	mock.recorder = &MockProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProber) EXPECT() *MockProberMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockProber) Probe(ctx context.Context, host string) (remote.ProbeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx, host)
	ret0, _ := ret[0].(remote.ProbeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockProberMockRecorder) Probe(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockProber)(nil).Probe), ctx, host)
}

// MockDaemonStatus is a mock of DaemonStatus interface.
type MockDaemonStatus struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonStatusMockRecorder
}

// MockDaemonStatusMockRecorder is the mock recorder for MockDaemonStatus.
type MockDaemonStatusMockRecorder struct {
	mock *MockDaemonStatus
}

// NewMockDaemonStatus creates a new mock instance.
func NewMockDaemonStatus(ctrl *gomock.Controller) *MockDaemonStatus {
	mock := &MockDaemonStatus{ctrl: ctrl}
	mock.recorder = &MockDaemonStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonStatus) EXPECT() *MockDaemonStatusMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockDaemonStatus) Status(ctx context.Context, host string) ([]daemon.HostStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, host)
	ret0, _ := ret[0].([]daemon.HostStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockDaemonStatusMockRecorder) Status(ctx, host interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockDaemonStatus)(nil).Status), ctx, host)
}
