// Code generated by MockGen. DO NOT EDIT.
// Source: dependency.go
//
// Generated by this command:
//
//	mockgen -source=dependency.go -destination=mocks/dependency_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSH is a mock of SSH interface.
type MockSSH struct {
	ctrl     *gomock.Controller
	recorder *MockSSHMockRecorder
	isgomock struct{}
}

// MockSSHMockRecorder is the mock recorder for MockSSH.
type MockSSHMockRecorder struct {
	mock *MockSSH
}

// NewMockSSH creates a new mock instance.
func NewMockSSH(ctrl *gomock.Controller) *MockSSH {
	mock := &MockSSH{ctrl: ctrl}
	mock.recorder = &MockSSHMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSH) EXPECT() *MockSSHMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockSSH) Run(ctx context.Context, host string, stdin []byte, argv ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, host, stdin}
	for _, a := range argv {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockSSHMockRecorder) Run(ctx, host, stdin any, argv ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, host, stdin}, argv...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSSH)(nil).Run), varargs...)
}

// MockTTY is a mock of TTY interface.
type MockTTY struct {
	ctrl     *gomock.Controller
	recorder *MockTTYMockRecorder
	isgomock struct{}
}

// MockTTYMockRecorder is the mock recorder for MockTTY.
type MockTTYMockRecorder struct {
	mock *MockTTY
}

// NewMockTTY creates a new mock instance.
func NewMockTTY(ctrl *gomock.Controller) *MockTTY {
	mock := &MockTTY{ctrl: ctrl}
	mock.recorder = &MockTTYMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTTY) EXPECT() *MockTTYMockRecorder {
	return m.recorder
}

// Interactive mocks base method.
func (m *MockTTY) Interactive(ctx context.Context, argv ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range argv {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Interactive", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Interactive indicates an expected call of Interactive.
func (mr *MockTTYMockRecorder) Interactive(ctx any, argv ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, argv...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interactive", reflect.TypeOf((*MockTTY)(nil).Interactive), varargs...)
}

// MockTerminfoSource is a mock of TerminfoSource interface.
type MockTerminfoSource struct {
	ctrl     *gomock.Controller
	recorder *MockTerminfoSourceMockRecorder
	isgomock struct{}
}

// MockTerminfoSourceMockRecorder is the mock recorder for MockTerminfoSource.
type MockTerminfoSourceMockRecorder struct {
	mock *MockTerminfoSource
}

// NewMockTerminfoSource creates a new mock instance.
func NewMockTerminfoSource(ctrl *gomock.Controller) *MockTerminfoSource {
	mock := &MockTerminfoSource{ctrl: ctrl}
	mock.recorder = &MockTerminfoSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerminfoSource) EXPECT() *MockTerminfoSourceMockRecorder {
	return m.recorder
}

// Infocmp mocks base method.
func (m *MockTerminfoSource) Infocmp(ctx context.Context, term string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Infocmp", ctx, term)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Infocmp indicates an expected call of Infocmp.
func (mr *MockTerminfoSourceMockRecorder) Infocmp(ctx, term any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infocmp", reflect.TypeOf((*MockTerminfoSource)(nil).Infocmp), ctx, term)
}
